language: python

python:
  - "2.6"
  - "2.7"
  - "3.2"
  - "3.3"
  - "3.4"
  - "3.5"

env:
  - BERKELEYDB_DIR=/usr

before_install:
  - sudo apt-get update -qq
  - sudo apt-get install -qq -y libdb5.1-dev

install: "pip install -r requirements.pip"

script: nosetests
